include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  language:
    strict-inference: true
  strong-mode:
    implicit-casts: false
  errors:
    missing_required_param: error
linter:
  rules:
    always_declare_return_types: true
    avoid_print: false
    constant_identifier_names: false
    directives_ordering: true
    prefer_relative_imports: true
